### ISSUE TITLE
Depency management

### ISSUE THREAD

**Issue by abelski** [ns-eien/jodtemplate#1]
Наверное стоит использовать какой нибудь трэвис CI и разместить библиотеку в мавен централе. Иначе не особо понятно как ее использовать в проектах которые собираются мавеном или грэдлом.

**Comment by ayakovlevgh** [comment]
Да, конечно. К релизу первой версии планируется написать документацию и выложить в maven central.

**Comment by abelski** [comment]
Когда планируется релиз?

**Comment by ayakovlevgh** [comment]
Думаю, что в марте. Более точных сроков сейчас не назову.

**Comment by abelski** [comment]
absolet
